#if !canImport(ObjectiveC)
import XCTest

extension ScmarkTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ScmarkTests = [
        ("testIterator", testIterator),
        ("testParser", testParser),
        ("testSimpleMarkdownToHTML", testSimpleMarkdownToHTML),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ScmarkTests.__allTests__ScmarkTests),
    ]
}
#endif
