name: Continuous Integration

on: [push, pull_request]

jobs:
  macos:
    name: macOS
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode:
          - 12
        action:
          - SwiftPM
          - codegen
    steps:
    - uses: actions/checkout@v2
    - name: Xcode version
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
    - name: Test
      run: make test-${{ matrix.action }}

  linux:
    name: Linux
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift:
          - 5.3
        distro:
          - bionic
          - focal
          - amazonlinux2
          - centos8
    steps:
    - uses: actions/checkout@v2
    - name: Test
      run: Scripts/docker.sh Scmark 'swift test -Xswiftc -warnings-as-errors' ${{ matrix.swift }} ${{ matrix.distro }}
