name: macOS

on: [push, pull_request]

jobs:
  macos:
    name: macOS
    runs-on: macOS-latest
    strategy:
      matrix:
        xcode:
          - 12
        action:
          - SwiftPM
          - codegen
    steps:
    - uses: actions/checkout@v2
    - name: Xcode version
      run: sudo xcode-select -s /Applications/Xcode_${{ matrix.xcode }}.app
    - name: Test
      run: make test-${{ matrix.action }}
